### ISSUE TITLE
weights not adding to 1 for MieMixture

### ISSUE THREAD

**Issue by dheligman** [xopto/pyxopto#2]
Hi,

I am currently running a simulation using MieMixture for my phase function. I created weights that should in theory add to one, but due to machine precision, they don't always do. My current fix to the issue is to add an np.round around the weight sum to trick it into accepting that the weights are off by a machine epsilon. 

Best,
Daniel

**Comment by bmiran** [comment]
Hi,
Indeed, the check in its current form is sensitive to machine precision. It will be fixed with the next commit. Until then, the workaround with np.round should be fine. The following fix for the input weights will work even if the weights are not intended to add up to 1:
wn = np.divide(w, np.sum(w)).

**Comment by xopto** [comment]
Hi,

Indeed, the check is sensitive to machine precision. It will be fixed with the next commit. Until then, the workaround with np.round should be fine. The following fix for the input weights will work even if the weights are not intended to add up to 1:

wn = np.divide(w, np.sum(w)).

**Comment by dheligman** [comment]
Thanks! Just wanted to make sure the fact that the sum was off by eps that it wouldn't cause a huge issue. :)
